Repository hexojs/hexo, pull requests merged in 2019-07, with the labels that each got.

#3598 chore: drop Node 6
  .travis.yml
  appveyor.yml
  package.json
Labels: Breaking Change

#3538 refactor: switch minimatch to micromatch
  lib/box/index.js
  lib/plugins/processor/common.js
  package.json
  test/scripts/box/box.js
Labels: enhancement

#3600 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request-improvement.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/question-help.md
Labels: discussion, documentation

#3612 feat(filter): use existing excerpt if possible
  lib/plugins/filter/after_post_render/excerpt.js
  test/scripts/filters/excerpt.js
Labels: feature-request
