Repository hexojs/hexo, pull requests merged in 2020-07, with the labels that each got.

#4405 feat: add benchmark script
  .gitignore
  .travis.yml
  test/benchmark.js
  test/benchmark.sh
  test/profiling.sh
Labels: enhancement

#4379 refactor(box): remove Bluebird.asCallback
  lib/box/file.js
  lib/box/index.js
  test/scripts/box/file.js
Labels: Breaking Change

#4436 perf(external_link): faster regexp & condition shorthand
  lib/plugins/filter/after_post_render/external_link.js
  lib/plugins/filter/after_render/external_link.js
Labels: #perfmatters

#4418 perf(tag): rendering optimization
  lib/extend/tag.js
  lib/hexo/post.js
  test/scripts/hexo/post.js
Labels: #perfmatters
