Repository hexojs/hexo, pull requests merged in 2020-04, with the labels that each got.

#4208 perf(meta_generator): avoid unnecessary check
  lib/plugins/filter/after_render/meta_generator.js
  test/scripts/filters/meta_generator.js
Labels: #perfmatters

#2903 Replace default swig engine with nunjucks
  lib/extend/tag.js
  lib/hexo/post.js
  lib/plugins/renderer/index.js
  lib/plugins/renderer/swig.js
  package.json
  test/scripts/console/generate.js
  test/scripts/extend/renderer.js
  test/scripts/helpers/partial.js
  test/scripts/hexo/hexo.js
  test/scripts/hexo/post.js
  test/scripts/hexo/render.js
  test/scripts/processors/asset.js
  test/scripts/renderers/index.js
  test/scripts/renderers/swig.js
  test/scripts/theme/theme.js
  test/scripts/theme/view.js
  test/scripts/theme_processors/source.js
  test/scripts/theme_processors/view.js
Labels: Breaking Change, enhancement

#4255 chore/ci: drop Node.js 8 and add Node.js 14
  .travis.yml
  appveyor.yml
  package.json
Labels: Breaking Change
