Repository hexojs/hexo, pull requests merged in 2020-06, with the labels that each got.

#4049 feat(extend/injector): bring up new extend Injector
  lib/extend/index.js
  lib/extend/injector.js
  lib/hexo/index.js
  lib/plugins/injector/index.js
  test/scripts/extend/index.js
  test/scripts/extend/injector.js
Labels: enhancement

#4359 fix(#3464): override permalink use the front-matter
  lib/plugins/filter/post_permalink.js
  lib/plugins/processor/post.js
  test/scripts/filters/post_permalink.js
  test/scripts/processors/post.js
Labels: Breaking Change

#3489 skip assets of unpublished posts and delete them if exist
  lib/plugins/processor/post.js
  test/scripts/processors/post.js
Labels: enhancement

#4174 feat(open_graph): drop 'keywords' option from front-matter
  lib/plugins/helper/open_graph.js
  test/scripts/helpers/open_graph.js
Labels: Breaking Change

#4278 feat: bring up config.updated_option
  lib/hexo/default_config.js
  lib/models/page.js
  lib/models/post.js
  lib/plugins/processor/asset.js
  lib/plugins/processor/post.js
  test/scripts/helpers/open_graph.js
  test/scripts/models/page.js
  test/scripts/models/post.js
  test/scripts/processors/asset.js
  test/scripts/processors/post.js
Labels: enhancement

#4377 perf(filter): shorthand syntax
  lib/extend/filter.js
Labels: #perfmatters
